python test_adamw_op.py
python test_elementwise_add_op.py
python test_reduce_op.py
python test_arange.py
python test_bitwise_op.py
python test_cast_op.py
python test_concat_op.py
python test_cross_entropy_loss.py
python test_elementwise_div_op.py
python test_einsum_op.py
python test_elementwise_pow_op.py
python test_embedding_deterministic.py
python test_empty_op.py
python test_compare_op.py
python test_expand_op.py
python test_fill_any_op.py
python test_flash_attention.py
python test_flatten_contiguous_range_op.py
python test_full_op.py
python test_gather_nd_op.py
python test_gaussian_random_op.py
python test_expand_op.py
python test_matmul_v2_op.py
python test_maximum_op.py
python test_mean_op.py
python test_multiply.py
python test_count_nonzero_api.py
python test_pow.py
python test_reshape_op.py
python test_activation_op.py
python test_slice_op.py
python test_activation_op.py
python test_squared_l2_norm_op.py
python test_squeeze2_op.py
python test_stack_op.py
python test_elementwise_sub_op.py
python test_sum_op.py
python test_transpose_op.py
python test_tril_triu_op.py
python test_uniform_random_op.py
python test_unsqueeze2_op.py
python test_where_op.py
python test_index_select_op.py
python test_index_put_op.py
python test_fold_op.py
